# Quan sát raw/processed của cafeF

In [110]:
import pandas as pd

raw_cafef = pd.read_parquet("../data/raw/cafef_board.parquet")
raw_cafef.head()

  ticker exchange           person_name             role source                  scraped_at
0    ABT     HOSE   Ông Nguyễn Văn Khải    Chủ tịch HĐQT  cafef  2026-03-03T17:44:42.349099
1    ABT     HOSE       Ông Hồ Quốc Lực  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
2    ABT     HOSE      Ông Phan Hữu Tài  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
3    ABT     HOSE  Ông Nguyễn Trung Anh  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
4    ABT     HOSE   Ông Nguyễn Khắc Hải  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099

In [109]:
processed_cafef = pd.read_parquet("../data/processed/processed_cafef.parquet")
processed_cafef.head()

  ticker exchange       person_name             role source                  scraped_at
0    ABT     HOSE   Nguyễn Văn Khải    Chủ tịch HĐQT  cafef  2026-03-03T17:44:42.349099
1    ABT     HOSE       Hồ Quốc Lực  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
2    ABT     HOSE      Phan Hữu Tài  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
3    ABT     HOSE  Nguyễn Trung Anh  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099
4    ABT     HOSE   Nguyễn Khắc Hải  Thành viên HĐQT  cafef  2026-03-03T17:44:42.349099

# Quan sát raw/processed của vietstock

In [111]:
raw_vietstock = pd.read_parquet("../data/raw/vietstock_board.parquet")
raw_vietstock.head()

  ticker exchange           person_name                        role   age  total_shares time_sticking     source           scraped_at closed_date
0    AAA     HOSE  Nguyễn Lê Thăng Long                      CTHĐQT  42.0             0    2021        vietstock  2026-03-03 22:18:54  29/06/2025
1    AAA     HOSE       Nguyễn Thị Tiện                      TVHĐQT  41.0             0    N/A         vietstock  2026-03-03 22:18:54  29/06/2025
2    AAA     HOSE        Phan Trí Nghĩa                      TVHĐQT  52.0             0       Độc lập  vietstock  2026-03-03 22:18:54  29/06/2025
3    AAA     HOSE       Nguyễn Lê Trung                         TGĐ  50.0             0    2007        vietstock  2026-03-03 22:18:54  29/06/2025
4    AAA     HOSE        Trần Thị Thoản  TVHĐQT/Phó TGĐ Thường trực  41.0             0    2009        vietstock  2026-03-03 22:18:54  29/06/2025

In [112]:
processed_vietstock = pd.read_parquet("../data/processed/processed_vietstock.parquet")
processed_vietstock.head()

  ticker exchange           person_name                                             role   age  total_shares time_sticking     source           scraped_at closed_date
0    AAA     HOSE  Nguyễn Lê Thăng Long                                    Chủ tịch HĐQT  42.0             0    2021        vietstock  2026-03-03 22:18:54  29/06/2025
1    AAA     HOSE       Nguyễn Thị Tiện                                  Thành viên HĐQT  41.0             0    N/A         vietstock  2026-03-03 22:18:54  29/06/2025
2    AAA     HOSE        Phan Trí Nghĩa                                  Thành viên HĐQT  52.0             0       Độc lập  vietstock  2026-03-03 22:18:54  29/06/2025
3    AAA     HOSE       Nguyễn Lê Trung                                    Tổng Giám đốc  50.0             0    2007        vietstock  2026-03-03 22:18:54  29/06/2025
4    AAA     HOSE        Trần Thị Thoản  Thành viên HĐQT / Phó Tổng Giám đốc thường trực  41.0             0    2009        vietstock  2026-03-03 22:18:54  29/06/2025

# Quan sát golden data

In [113]:
golden_data = pd.read_parquet("../data/final/golden_board.parquet")

golden_data.head()

  ticker exchange       person_name               role   age  total_shares time_sticking source_agreement  confidence_score                   data_quality           scraped_at
0    A32    UPCOM  Đặng Thị Thúy Hà     Thành viên BKS  48.0        5300.0    2000                   both              1.00            Perfect (Full Data)  2026-03-04 01:27:52
1    A32    UPCOM    Dương Hoài Nam     Thành viên BKS  55.0        1200.0    1994                   both              1.00            Perfect (Full Data)  2026-03-04 01:27:52
2    A32    UPCOM      Hà Ngọc Oanh         Trưởng BKS  55.0        8500.0    1993                   both              1.00            Perfect (Full Data)  2026-03-04 01:27:52
3    A32    UPCOM  Hoàng Mạnh Cường     Kế toán trưởng   NaN           0.0    N/A          vietstock_only              0.80     Acceptable (Single Source)  2026-03-04 01:27:52
4    A32    UPCOM   Ngô Thành Thắng  Phó Chủ tịch HĐQT  49.0      886100.0    1996               conflict              0.85  Needs Verification (Conflict)  2026-03-04 01:27:52